options:
    top: &7&m[---[&4&l&mRules&7&m]---]
 
command /rules:
    trigger:
        send "{@top}"
        send "&a- No spamming"
        send "&a- No NSFW or controvercial topics"
        send "&a- Mo toxicity"
        send "&a- No using softwares / clients for unfair advantages"
        send "&a- No piechart"
        send "&a- No alting for rewards"
        send "&a- No exploiting bugs / glitches"
        send "&a- Only talk in english"
        send "&a- Use common sense"
        send "&a- No disrespect to players / staff"
        send "&a- No swat / ddos / dox threats"
        send "&a- No discriminating"
        send "&a- No swearing / cursing / sluring"
        send "&a- No leaking personal information"
        send "&a- No avoiding punishments"
        send "&a- No jokes about others racial, sexual identity"
        send "&a- No IP grabbing"
        send "&a- Join MyhsticMC!"
        send "{@top}"